[project]
name = "password-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.7",
    "ruff>=0.12.0",
    "streamlit>=1.46.0",
]
